### ISSUE TITLE
./temp/ file not found

### ISSUE THREAD

**Issue by dhalvor** [ajshajib/LensingETC#1]
FileNotFoundError when after computing  first MCMC.
![image](https://user-images.githubusercontent.com/97866735/160769863-b2877ef3-5348-47ad-a17e-8a2f76b084f3.png)
Not familiar with how temp files/directories work so couldn't figure it out.

**Comment by ajshajib** [comment]
The error was because the "temp" folder was not there within directory. I added the folder to the Git structure via 72ba5e67e265eb3d75b1411b2953ff1cea563a81, but you can also choose to save the output files anywhere you like by using the `save_directory` argument in the relevant functions.
